In [1]:
import pandas as pd
import re

In [2]:
data = pd.read_csv('data/hanan.csv')
data

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1981638609838195120,Sun Oct 26 01:32:52 +0000 2025,0,@didiek_murdock ada yg sepemikiran ternyata ka...,1982259099988603011,NaN,didiek_murdock,in,NaN,0,0,0,https://x.com/undefined/status/198225909998860...,515265372,NaN
1,1982258955155042525,Sun Oct 26 01:32:18 +0000 2025,0,bener2 perihh lidahkuu jirr apaa ak di adzab k...,1982258955155042525,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198225895515504...,1494859735559913476,NaN
2,1982256576217145708,Sun Oct 26 01:32:05 +0000 2025,0,Orang-orang kagak jelas kaya Budie arie Bahlil...,1982258901195395460,NaN,fallingmonstar,in,NaN,0,1,0,https://x.com/undefined/status/198225890119539...,1490361012062547968,NaN
3,1982029068427288962,Sun Oct 26 01:31:41 +0000 2025,1,@Koruptor_keDUA @yaniarsim Gus Bahlil Alpapuani,1982258800527904969,NaN,Koruptor_keDUA,in,NaN,0,0,0,https://x.com/undefined/status/198225880052790...,1635083361718013952,NaN
4,1981891459113521502,Sun Oct 26 01:31:28 +0000 2025,0,@txtdrimedia Kalau Bahlil ini masuk golongan u...,1982258745905422581,NaN,txtdrimedia,in,NaN,0,0,0,https://x.com/undefined/status/198225874590542...,1897985755676655618,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,1981919796376785206,Sat Oct 25 03:04:36 +0000 2025,0,Fotonya gak enak diliat kek bahlil,1981919796376785206,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198191979637678...,4807033092,NaN
1008,1981687889244385604,Sat Oct 25 03:04:25 +0000 2025,0,@randomable_ Baik hati sekali gus bahlil ini,1981919750545604726,NaN,randomable_,in,NaN,0,0,0,https://x.com/undefined/status/198191975054560...,451134294,NaN
1009,1981919668916150781,Sat Oct 25 03:04:06 +0000 2025,0,Bahlil: belum tentu orang ganteng itu cerdas! ...,1981919668916150781,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198191966891615...,747644790129500160,NaN
1010,1981919556076744749,Sat Oct 25 03:03:39 +0000 2025,1,Bahlil mah enak ga pusing kostum helloween -_-,1981919556076744749,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198191955607674...,1466250199089614848,NaN
1011,1981753883484676506,Sat Oct 25 03:03:07 +0000 2025,0,@jorgianaaa Bubarkan Bahlil,1981919422593081709,NaN,jorgianaaa,in,NaN,0,0,0,https://x.com/undefined/status/198191942259308...,61203621,NaN

In [3]:
def cleansing(sent):
    string = sent.lower()
    string = re.sub(r'http\S+', '', string)  # Remove URLs
    string = re.sub(r'@\w+', '', string)     # Remove mentions
    string = re.sub(r'#\w+', '', string)     # Remove hashtags
    string = re.sub(r'\d+', '', string)      # Remove angka
    string = re.sub(r'[^\w\s]', '', string)  # Remove punctuation
    return string

In [4]:
data['full_text'] = data.full_text.apply(cleansing)
data.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1981638609838195120,Sun Oct 26 01:32:52 +0000 2025,0,ada yg sepemikiran ternyata kalo bahlil mirip...,1982259099988603011,NaN,didiek_murdock,in,NaN,0,0,0,https://x.com/undefined/status/198225909998860...,515265372,NaN
1,1982258955155042525,Sun Oct 26 01:32:18 +0000 2025,0,bener perihh lidahkuu jirr apaa ak di adzab ka...,1982258955155042525,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/198225895515504...,1494859735559913476,NaN
2,1982256576217145708,Sun Oct 26 01:32:05 +0000 2025,0,orangorang kagak jelas kaya budie arie bahlil ...,1982258901195395460,NaN,fallingmonstar,in,NaN,0,1,0,https://x.com/undefined/status/198225890119539...,1490361012062547968,NaN
3,1982029068427288962,Sun Oct 26 01:31:41 +0000 2025,1,gus bahlil alpapuani,1982258800527904969,NaN,Koruptor_keDUA,in,NaN,0,0,0,https://x.com/undefined/status/198225880052790...,1635083361718013952,NaN
4,1981891459113521502,Sun Oct 26 01:31:28 +0000 2025,0,kalau bahlil ini masuk golongan udah jelek to...,1982258745905422581,NaN,txtdrimedia,in,NaN,0,0,0,https://x.com/undefined/status/198225874590542...,1897985755676655618,NaN

In [5]:
data = data[['full_text']]
data.head

<bound method NDFrame.head of                                               full_text
0      ada yg sepemikiran ternyata kalo bahlil mirip...
1     bener perihh lidahkuu jirr apaa ak di adzab ka...
2     orangorang kagak jelas kaya budie arie bahlil ...
3                                  gus bahlil alpapuani
4      kalau bahlil ini masuk golongan udah jelek to...
...                                                 ...
1007                 fotonya gak enak diliat kek bahlil
1008                    baik hati sekali gus bahlil ini
1009  bahlil belum tentu orang ganteng itu cerdas ya...
1010       bahlil mah enak ga pusing kostum helloween _
1011                                    bubarkan bahlil

[1012 rows x 1 columns]>

In [6]:
data.to_csv('data/clean_hanan.csv', index=False)